#!/bin/sh

echo '===pre-commit-resx-checker===='

git diff --cached --name-status --diff-filter=ACMR | while read STATUS FILE ; do
	if [  ${FILE: -5} == ".resx"  ]; then
		echo "$FILE"		
		git diff --unified=1 HEAD $FILE | tail -5 
	fi
done > diff.diff